FROM node:20-alpine as nodeimage
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM gcr.io/distroless/nodejs20-debian12
WORKDIR /app
COPY --from=nodeimage /app/node_modules ./node_modules
COPY app.js .
COPY package.json ./
EXPOSE 8080
USER 65532
CMD ["app.js","development"]
