name : demo action pipeline
on : 
  push :
    branches : ["main"]
  pull_request :
    branches : ["main"]
  workflow_dispatch: 
jobs :
  demo_check :
    runs on : ubuntu-latest
    steps :
       - name : demo pipeline check
       run : echo "demo pipeline check"
