name: pipeline_name

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  sonar_qube:
    runs-on: [self-hosted, ubuntu-runner]
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Clone code
        uses: actions/checkout@v7

      - name: Sonarqube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        with:
          args: >
            sonar.projectKey=NodeJS_App
            sonar.sources=.
            sonar.host.url=${{ vars.SONAR_HOST_URL }}
            sonar.login=${{ secrets.SONAR_TOKEN }}
            sonar.qualitygate.wait=true

  docker:
    runs-on: [self-hosted, ubuntu-runner]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: prod
    
    steps:
      - name: Clone code
        uses: actions/checkout@v7

      # Uses the repository-level custom action syntax exactly as shown in the screenshot
      - name: Login to Docker Hub
        uses: arunkumar81096/featurebranch3/.github/actions/docker build and push@action
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
