name : Demo-run-application
on:
     push:
       branches: ["main"]
jobs:
     demo:
        runs-on : [self-hosted, Linux]
        steps:
          - name : clone code 
            uses: actions/checkout@v7
          - name: node-install
            uses: actions/setup-node@v6
            with:
               node-version: 24
          - name: install_dependencies
            run: npm install 
          - name: run application 
            run: |
               node app.js &
               sleep 3
               curl http://localhost:8080
               curl http://localhost:8080/health
               pkill -f "node app.js"
