name: docker-push
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  node:
    runs-on: [self-hosted, ubuntu-runner]
    steps:
      - name: clone-code
        uses: actions/checkout@v4

      # 1. Extracted short SHA and assigned the step ID as 'commit_tag'
      - name: Set Short SHA
        id: commit_tag
        run: echo "sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ak81096
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # 2. Build the image directly with the tag
      - name: Build Docker image
        run: |
          docker build -t ak81096/ak81096:${{ steps.commit_tag.outputs.sha }} .
          
      # 3. Push the image using the identical matching tag structure
      - name: push image
        run: |
          docker push ak81096/ak81096:${{ steps.commit_tag.outputs.sha }}
