name : sonarqube-test
on:
    pull_request:
      branches: ["main"]
    workflow_dispatch:
jobs:
    node:
      runs-on : [self-hosted,Linux]
      steps:
        - name: clone-code
          uses: actions/checkout@v7
        - name: sonarqube scan 
          uses: sonarsource/sonarqube-scan-action@v8
          with:
           args: >
             -Dsonar.projectKey=Revamp_assignment \
             -Dsonar.sources=. \
             -Dsonar.host.url=http://localhost:9000
              
