name: sonarqube-test
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  node:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: clone-code
        uses: actions/checkout@v4

      - name: sonarqube scan 
        uses: sonarsource/sonarqube-scan-action@v3
        with:
          args: >
            -Dsonar.projectKey=Revamp_assignment
            -Dsonar.sources=.
            -Dsonar.host.url=http://54.80.169.71:9000
            -Dsonar.token=sqp_21ae70775fe7bc39cf4cc5c1144f0568c8799aa4
